import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const main=fs.readFileSync(process.env.LIVE_SHORTCUT_MAIN_SOURCE || new URL('../electron/main.js',import.meta.url),'utf8'),ast=ts.createSourceFile('main.js',main,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
const extract=name=>ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name).getText(ast);
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function setup(){let now=1000,hotkey='F8',registered=true,active=false;const pending=[],handlers=[];const defer=()=>new Promise((resolve,reject)=>pending.push({resolve,reject}));
 const context=vm.createContext({liveToggleRevision:0,liveShortcutError:undefined,liveShortcut:{key:'F8',registered:false,reason:''},lastLiveShortcutAt:0,Date:{now:()=>now},Error,liveConfig:{snapshot:()=>({hotkey})},globalShortcut:{register(key,callback){handlers.push(callback);return registered;},unregister(){}},liveVoice:{hasActive:()=>active,start:defer,stop:defer},wakeQuitUnknown:false,voiceConfigurationPending:false,panelHiding:false,voiceInput:undefined,wakeVoice:undefined,pinned:false,openPanel(){},publish(){}});
 for(const name of ['stopWakeVoice','toggleLive','registerLiveShortcut'])vm.runInContext(extract(name),context);context.registerLiveShortcut();return {context,pending,handlers,advance(){now+=450;},key(value,allowed=true){hotkey=value;registered=allowed;context.registerLiveShortcut();},active(value){active=value;}};}

test('current registered shortcut retry clears only its old failure',async()=>{const s=setup();s.handlers[0]();await flush();s.pending[0].reject(Error('first failed'));await flush();assert.equal(s.context.liveShortcut.reason,'first failed');s.advance();s.handlers[0]();await flush();s.pending[1].resolve('original value');await flush();assert.equal(s.context.liveShortcut.reason,'');});
test('successful mouse retry clears its prior shortcut failure and preserves original value',async()=>{const s=setup();s.handlers[0]();await flush();s.pending[0].reject(Error('shortcut failed'));await flush();const mouse=s.context.toggleLive();await flush();s.pending[1].resolve('original value');assert.equal(await mouse,'original value');assert.equal(s.context.liveShortcut.reason,'');});
for(const [key,allowed,wanted] of [['F9',true,'F9 用于记事本写入确认，请在 Live 设置中更换快捷键'],['F24',false,'F24 已被占用，请在 Live 设置中更换快捷键'],['F24',true,'']])test(`old shortcut failure cannot overwrite newer ${key}/${allowed} registration`,async()=>{const s=setup();s.handlers[0]();await flush();s.key(key,allowed);s.pending[0].reject(Error('old failed'));await flush();assert.equal(s.context.liveShortcut.reason,wanted);});
test('late old start success cannot clear newer shortcut stop failure',async()=>{const s=setup();s.handlers[0]();await flush();s.active(true);s.advance();s.handlers[0]();await flush();s.pending[1].reject(Error('new stop failure'));await flush();s.pending[0].resolve();await flush();assert.equal(s.context.liveShortcut.reason,'new stop failure');});
test('late old failure cannot overwrite newer successful mouse operation',async()=>{const s=setup();s.handlers[0]();await flush();s.active(true);const stop=s.context.toggleLive();await flush();s.pending[1].resolve();await stop;s.pending[0].reject(Error('old failed'));await flush();assert.equal(s.context.liveShortcut.reason,'');});
test('pending retry success preserves new occupied registration reason',async()=>{const s=setup();s.handlers[0]();await flush();s.pending[0].reject(Error('first failed'));await flush();s.advance();s.handlers[0]();await flush();s.key('F24',false);s.pending[1].resolve();await flush();assert.equal(s.context.liveShortcut.reason,'F24 已被占用，请在 Live 设置中更换快捷键');});
test('400ms shortcut debounce still suppresses duplicate operation',async()=>{const s=setup();s.handlers[0]();s.handlers[0]();await flush();assert.equal(s.pending.length,1);s.pending[0].resolve();await flush();});
test('active stop retains priority over configuration and panel guard and original error identity',async()=>{const s=setup();s.active(true);s.context.voiceConfigurationPending=true;s.context.panelHiding=true;const stop=s.context.toggleLive();await flush();assert.equal(s.pending.length,1);const error=Error('release unknown');s.pending[0].reject(error);await assert.rejects(stop,e=>e===error);assert.equal(s.context.liveShortcut.reason,'');});
test('current mouse failure remains an original rejection without owning shortcut feedback',async()=>{const s=setup();const start=s.context.toggleLive();await flush();const error=Error('mouse failed');s.pending[0].reject(error);await assert.rejects(start,e=>e===error);assert.equal(s.context.liveShortcut.reason,'');});

test('retired registration callback success cannot clear new registration failure',async()=>{const s=setup();s.key('F24');s.handlers[1]();await flush();s.pending[0].reject(Error('new registration failure'));await flush();s.advance();s.handlers[0]();await flush();s.pending[1].resolve();await flush();assert.equal(s.context.liveShortcut.reason,'new registration failure');});
